customers/urls.py
from django.urls import path
from accounts import views as accViews
from . import views

app_name = 'customers'

urlpatterns = [
    path('', accViews.customerDashboard, name="customer"),
    path('profile/' , views.customer_profile, name="cprofile"),
    path('myorders/', views.my_orders, name='cust-myorders'),
    path('order-detail/<int:pk>', views.order_detail, name='order-detail'),
]

mvstore/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from marketplace import views as mpViews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home") ,
    path('about/', views.about, name="about") ,
    path('accounts/', include('accounts.urls' ,  namespace="accounts")),
    path('customer/', include('customers.urls', namespace="customer")),
    path('vendor/', include('vendor.urls' ,  namespace="vendor")),
    path('marketplace/', include('marketplace.urls')) ,
    path('checkout/', mpViews.checkout, name="checkout"),
    path('orders/', include('orders.urls')) ,
    path('search/', mpViews.search, name="search" )
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('place-order/', views.place_order, name="place-order"),
    path('payments/', views.payments, name="payments"),
    path('order-complete/', views.order_complete, name='order-complete')
    # path('', views.orders, name="orders"),
]

customers/models.py
from django.db import models

# Create your models here.

customers/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.forms import UserProfileForm , UserInfoForm
from accounts.models import UserProfile
from orders.models import Order, OrderedProduct
import simplejson as json


@login_required(login_url='accounts:login')
def customer_profile(request):

    profile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        profile_form = UserProfileForm(request.POST, request.FILES, instance=profile)
        user_form = UserInfoForm(request.POST, instance=request.user)

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save()
            user_form.save()
            messages.success(request, 'Profile Updated')
            return redirect('customer:cprofile')
        else:
            print(profile_form.errors)
            print(user_form.errors)
    else:
        profile_form = UserProfileForm(instance=profile)
        user_form = UserInfoForm(instance=request.user)

    context = {
        'profile': profile,
        'profile_form': profile_form,
        'user_form' : user_form
    }
    return render(request, 'customers/cprofile.html' , context)

def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    context = {
        'orders':orders
    }
    return render(request, 'customers/myorders.html', context)

def order_detail(request, pk=None):
    order = get_object_or_404(Order, pk=pk, is_ordered=True)
    ordered_products = OrderedProduct.objects.filter(order=order)

    subtotal = 0
    for item in ordered_products:
        subtotal += (item.price * item.quantity)
    tax_data = json.loads(order.tax_data)

    context = {
        'order':order,
        'ordered_products': ordered_products,
        'subtotal': subtotal,
        'tax_data' : tax_data

    }

    return render(request, 'customers/orderdetail.html', context)

templates/customers/cover.html
{% load static %}

<div class="page-section restaurant-detail-image-section background-header">
    <!-- Container Start -->
    <div class="container">
      <!-- Row Start -->
      <div class="row">
        <!-- Column Start -->
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
          <div class="company-info-detail">
            <div class="company-info">
              <div class="img-holder">
                <figure>
                  {% if customer.user_profile_picture %}
                  <img src="{{ user_profile.profile_picture.url }}" alt="">
                  {% else %}
                  <img src="{% static 'extra-images/customer-default.PNG' %}" alt="">
                  {% endif %}

                </figure>
              </div>

              <div class="text-holder">
                <span class="restaurant-title"> Name : {{ user.first_name }} {{ user.last_name }}</span>
                <div class="text">
                  <i class="icon-location"></i>
                  <p>Tel : 01132 123 215  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- Column End -->
      </div>
      <!-- Row End -->
    </div>
    <!-- Container End -->
  </div>

templates/customers/cprofile.html
{% extends 'base.html' %}
{% load static %}


{% block page-style %}
	{% if user_profile.cover_photo %} 
		<style>
			.background-header {background-image: url('{{ user_profile.cover_photo.url }}');}
		</style>
	{% else %}
		<style>
			.background-header {background-image: url('{% static "images/default-cover.png" %}');}
		</style>
	{% endif %}
{% endblock %}


{% include 'includes/alerts.html' %}
{% block content  %}
<!-- Main Section Start -->
<div class="main-section">
  {% include 'customers/cover.html' %}
  <div class="page-section account-header buyer-logged-in">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12" >
<!-- load the sidebar here -->

        {% include 'includes/sidebar-c.html' %}



        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
          <div class="user-dashboard loader-holder">
            <div class="user-holder">
              <div class="text-uppercase"><h5>Profile Settings</h5></div>

              <form action="{% url 'customers:cprofile' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-fields-set">
                  <ul>
                    <li>
                      <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                          <div class="restaurant-info">
                            <div class="img-holder">
                              <ul class="foodbakery-gallery-holder">
                                <li class="gal-img">
                                  <div class="drag-list">
                                    <div class="item-thumb">
                                      {% if customer.user_profile_picture %}
                                        <img class="thumbnail" src="{{user_profile.profile_picture.url}}" alt="Profile Picture">
                                      {% else %}
                                        <img class="thumbnail" src="{% static 'images/default-profile.PNG' %}" alt="Profile Picture">
                                      {% endif %}
                                    </div>
                                  </div>
                                </li>
                              </ul>
                            </div>
                            <div class="text-holder">
                              <label>Update Profile Picture</label>
                              <div class="upload-gallery">
                                {{ profile_form.profile_picture }}
                              </div>
                              <label class="text-danger">{{ profile_form.profile_picture.errors }}</label>
                            </div>
                          </div>

                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                          <div class="restaurant-info">
                            <div class="img-holder">
                              <ul class="foodbakery-gallery-holder">
                                <li class="gal-img">
                                  <div class="drag-list">
                                    <div class="item-thumb">
                                    {% if customer.user_profile.cover_photo %} 
                                      <img class="thumbnail" src="{{ user_profile.cover_photo.url }}" alt="Main Profile Photo">
                                    {% else %}
                                      <img class="thumbnail" src="{% static 'images/default-cover.PNG' %}" alt="Main Cover Photo">
                                    {% endif %}
                                    </div>
                                  </div>
                                </li>
                              </ul>
                            </div>
                            <div class="text-holder">
                              <label>Update Cover Photo</label>
                              <div class="upload-gallery">
                                {{ profile_form.cover_photo }}
                              </div>
                              <label class="text-danger">{{ profile_form.cover_photo.errors }}</label>
                            </div>
                          </div>

                        </div>

                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>First Name *</label>
                              {{ user_form.first_name }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>Last Name *</label>
                              {{ user_form.last_name }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>Phone Number *</label>
                              {{ user_form.phone_number }}
                          </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>Address</label>
                              {{ profile_form.address }}
                              <small class="text-muted float-right">powered by Google</small>
                          </div>
                        </div>


                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>City </label>
                              {{ profile_form.city }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>State </label>
                              {{ profile_form.state }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>Country </label>
                              {{ profile_form.country }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>Postcode </label>
                              {{ profile_form.postcode }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>longitude </label>
                              {{ profile_form.longitude }}
                          </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                          <div class="field-holder">
                            <label>Latitude </label>
                              {{ profile_form.latitude }}
                          </div>
                        </div>


                      </div>
                    </li>
                  </ul>
                  <div>
                    <div class="field-holder">
                      <div class="payment-holder input-button-loader">
                        <input class="update-restaurant" type="submit" value="Update User">
                      </div>
                    </div>
                  </div>
                </div>
              </form>




            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Main Section End -->



{% endblock %}

templates/customers/myorders.html
{% extends 'base.html' %}
{% load static %}

{% include 'includes/alerts.html' %}
{% block content  %}
<!-- Main Section Start -->
<div class="main-section">

  <div class="page-section account-header buyer-logged-in">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
<!-- load the sidebar here -->

        {% include 'includes/sidebar-c.html' %}

        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
          <div class="user-dashboard loader-holder">
            <div class="user-holder">
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                  <div class="element-title has-border right-filters-row">
                    <h5>My Orders</h5>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                  <div class="user-orders-list">
                    <div class="responsive-table">
                      <table class="table table-hover  table-borderless">
                        <thead>
                          <tr>
                            <th scope="col">Order #</th>
                            <th scope="col">Name</th>
                            <th scope="col">Phone</th>
                            <th scope="col">Total</th>
                            <th scope="col">Status</th>
                            <th scope="col">Date</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for order in orders %}
                          <tr>
                            <td><b><a href="{% url 'customer:order-detail' order.id %}" class="text-dark">  {{order.order_number }}</a></b></td>
                            <td>{{ order.name }}</td>
                            <td>{{ order.phone }}</td>
                            <td>{{ order.total }}</td>
                            <td>{{ order.status }}</td>
                            <td>{{ order.created_at }}</td>
                            <td><a href="{% url 'customers:order-detail' order.id %}" class="btn btn-info">Details</a></td>
                          </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>

            </div> <!--user holder div end-->

          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Main Section End -->



{% endblock %}

templates/customers/orderdetail.html
{% extends 'base.html' %}
{% load static %}

{% include 'includes/alerts.html' %}
{% block content  %}
<!-- Main Section Start -->
<div class="main-section">

  <div class="page-section account-header buyer-logged-in">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
<!-- load the sidebar here -->

        {% include 'includes/sidebar-c.html' %}

        </div>
        <div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
          <div class="user-dashboard loader-holder">
            <div class="user-holder">

                <div class="row">

                        <h5>Order Detail for {{ order }}</h5>
           
<!--Order complete layout-->

<div class="col-md-12">
            <div class="bg-white p-4">
                <img src="{% static 'logo/main-logo.png'  %}" alt="main-logo" width="">
                <div class="row">
                    <div class="col-md-12 text-right">
                        <p class="mb-0">{{order.name}}</p>
                        <p class="mb-0">{{order.address}}</p>
                        <p class="mb-0">{{order.phone}}</p>
                        <p class="mb-0">{{order.email}}</p>
                    </div>
                </div>
                <hr>
                <div class="d-flex justify-content-between">
                    <div>
                        <span class="d-block">Order Date:</span><span class="font-weight-bold">{{ order.created_at }}</span>
                    </div>
                    <div>
                        <span class="d-block">Order Number:</span><span class="font-weight-bold">{{ order.order_number }}</span>
                    </div>
                    <div>
                        <span class="d-block">Payment Method:</span><span class="font-weight-bold">{{ order.payment_method }}</span>
                    </div>
                    <div>
                        <span class="d-block">transaction_id:</span><span class="font-weight-bold">{{ order.payment.transaction_id }}</span>
                    </div>
                </div>
                <hr>
<!--Order Item Info -->
                <table class="table table-borderless">
                    <tbody>
                    {% for item in ordered_products %}
                        <tr>
                            <td style="width: 60px;"><img src="{{ item.product.image.url }}" width="40"  alt=""> </td>
                            <td style="padding: 0; text-align: left; padding-left: 10px;">
                                <b>{{ item.product }}</b> 
                                <a href="{% url 'vendor-detail' item.product.vendor.vendor_slug %}" class="badge badge-info">{{ item.product.vendor.vendor_name }}</a>
                            </td>
                            <td>{{ item.quantity }} Qty </td>
                            <td>{{ item.product.price }} </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
<!-- Display Totals & Taxes etc-->
                <div class="row">
                    <div class="d-flex justify-content-center col-md-6">
                        <img src="{% static 'images/paid.png' %}" width="100">
                    </div>

                    <div class="col-md-6" style="background-color: rgb(151, 158, 158); color: white;">
                        <ul>
                            <li style="list-style-type: none;">
                                Subtotal
                                <span class="price float-right">
                                    <span class="currency">£</span>
                                    <span id="subtotal"> {{ subtotal|floatformat:2}} </span>
                                </span>
                            </li>
                            {% for key, value in tax_data.items %}
                                {% for i, j in value.items %}
                                    <li style="list-style-type: none;">
                                        {{ key }} <small>({{ i }}%)</small>
                                        <span class="price float-right">
                                            <span class="currency">£</span>
                                            <span id="tax-{{ key }}"> {{ j }} </span>
                                        </span>
                                    </li>
                                {% endfor %}
                            {% endfor %}
                            <li style="list-style-type: none; font-weight: 600;">
                                TOTAL
                                <span class="price float-right ">
                                    <span class="currency">£</span>
                                    <span id="total"> {{ order.total }} </span>
                                </span>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


<!--end of detail -->
                </div>
            </div><!--user holder div end-->
          </div>
        </div> <!--end of col-lg-9  -->

      </div>
    </div>
  </div>
</div>
<!-- Main Section End -->



{% endblock %}