accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.myAccount ),
    path('registeruser/', views.registerUser, name='registeruser'),
    path('registervendor/', views.registerVendor, name='registervendor'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('myaccount/', views.myAccount, name='myaccount'),
    path('customerdashboard/', views.customerDashboard, name='customerdashboard'),
    path('vendordashboard/', views.vendorDashboard, name='vendordashboard'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>' , views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

marketplace/urls.py
from django.urls import path
from . import views

# app_name = 'marketplace'

urlpatterns = [
	path('', views.marketplace, name='marketplace'),
	path('cart/', views.cart, name='cart'),
	path('<slug:vendor_slug>/' , views.vendor_detail, name="vendor-detail"), 
	path('add-to-cart/<int:product_id>', views.add_to_cart, name="add-to-cart"),
	path('remove-cart-item/<int:product_id>', views.remove_cart_item, name="remove-cart-item"),
	path('delete-cart-item/<int:cart_id>', views.delete_cart_item, name="delete-cart-item"),

]

mvstore/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from marketplace import views as mpViews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home") ,
    path('about/', views.about, name="about") ,
    path('accounts/', include('accounts.urls' ,  namespace="accounts")),
    path('customer/', include('customers.urls', namespace="customer")),
    path('vendor/', include('vendor.urls' ,  namespace="vendor")),
    path('marketplace/', include('marketplace.urls')) ,
    path('checkout/', mpViews.checkout, name="checkout"),
    path('orders/', include('orders.urls')) ,
    path('search/', mpViews.search, name="search" )
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('place-order/', views.place_order, name="place-order"),
    path('payments/', views.payments, name="payments"),
    path('order-complete/', views.order_complete, name='order-complete')
    # path('', views.orders, name="orders"),
]

marketplace/models.py
from django.db import models
from accounts.models import User
from menu.models import Product

class Cart(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField()
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.user

class Tax(models.Model):
	tax_type = models.CharField(max_length=20, unique=True)
	tax_percentage = models.DecimalField(decimal_places=2, max_digits=4, verbose_name='tax percentage %' )
	is_active = models.BooleanField(default=True)

	class Meta:
		verbose_name_plural = "Tax"

	def __str__(self):
		return self.tax_type

marketplace/views.py
from django.shortcuts import redirect, render, get_object_or_404  
from django.http import HttpResponse , JsonResponse
from django.db.models import Prefetch
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from datetime import date , datetime
from django.contrib.gis.geos import GEOSGeometry
from django.contrib.gis.measure import D  # for Distance
from django.contrib.gis.db.models.functions import Distance
from django.core.exceptions import ObjectDoesNotExist

from vendor.models import Vendor , OpeningHour
from menu.models import Category , Product
from .models import Cart
from orders.forms import OrderForm
from accounts.models import UserProfile
from .context_processors import get_cart_counter, get_cart_amounts


def marketplace(request):
	vendors = Vendor.objects.filter(is_approved=True, user__is_active=True)
	vendro_count = vendors.count()
	context = {'vendors' : vendors , 'vendro_count':vendro_count }

	return render(request, 'marketplace/marketplace.html' , context )


def vendor_detail(request, vendor_slug):
	vendor = get_object_or_404(Vendor, vendor_slug=vendor_slug)
	categories = Category.objects.filter(vendor=vendor).prefetch_related(
		Prefetch('products' , queryset= Product.objects.filter(is_available=True)))
	
	opening_hours = OpeningHour.objects.filter(vendor=vendor).order_by('day', 'from_hour')
	today = date.today().isoweekday()
	hours_today = OpeningHour.objects.filter(vendor=vendor, day=today ).order_by('from_hour')

	if request.user.is_authenticated:
		cart_items = Cart.objects.filter(user=request.user)
	else:
		cart_items = None

	context = { 
		'vendor':vendor , 
		'categories' : categories ,
		'cartItems' : cart_items,
		'opening_hours': opening_hours ,
		'hours_today' : hours_today ,
		}
	
	return render(request, 'marketplace/vendor-detail.html' , context)


def add_to_cart(request, product_id):
    if request.user.is_authenticated:
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':
            # Check if product exists
            try:
                product = Product.objects.get(id=product_id)
                # Check if product already in cart
                try:
                    check_cart = Cart.objects.get(user=request.user, product=product)
                    check_cart.quantity += 1
                    check_cart.save()
                    return JsonResponse({'status': 'Success', 'message': 'Cart Quantity Increased', 
	                    		'cart_counter':get_cart_counter(request), 
	                    		'itemQty' : check_cart.quantity  ,
	                    		'cart_amount' : get_cart_amounts(request) 
	                    		})
                except Cart.DoesNotExist:
                    check_cart = Cart.objects.create(user=request.user, product=product, quantity=1)
                    return JsonResponse({'status': 'Success', 'message': 'Product Added to cart', 
	                    		'cart_counter':get_cart_counter(request),  
	                    		'itemQty' : check_cart.quantity ,
	                    		'cart_amount' : get_cart_amounts(request) 
	                    	})
            except Product.DoesNotExist:
                return JsonResponse({'status': 'Failed', 'message': 'Product Does not exist'})
        else:
            return JsonResponse({'status': 'Failed', 'message': 'Invalid request'})
    else:
    	return JsonResponse({'status':'login_required', 'message':'Please Login to continue'})


def remove_cart_item(request, product_id):
	if request.user.is_authenticated:
		if request.headers.get('x-requested-with') == 'XMLHttpRequest':
			try:
				product = Product.objects.get(id=product_id)
				try:
					check_cart = Cart.objects.get(user=request.user, product=product)
					if check_cart.quantity > 1:
						check_cart.quantity -= 1
						check_cart.save()
					else:
						check_cart.delete()
						check_cart.quantity = 0
					return JsonResponse({'status' : 'Success', 
							'cart_counter': get_cart_counter(request), 
							'itemQty' : check_cart.quantity ,
							'cart_amount' : get_cart_amounts(request)  
						})
				except Cart.DoesNotExist:
					return JsonResponse({'status': 'Failed', 'message': 'You do not have this item in your cart !'  })

			except Product.DoesNotExist:
				return JsonResponse({'status': 'Failed', 'message': 'Product Does not exist'})
		else:
			return JsonResponse({'status': 'Failed', 'message': 'Invalid Request'})
	else:
		return JsonResponse({'status': 'login_required', 'message': 'Please Login to continue'})

@login_required(login_url='accounts:login')
def cart(request):
	cart_items = Cart.objects.filter(user=request.user).order_by('product')
	context = { 'cart_items':cart_items }

	return render(request, 'marketplace/cart.html' , context)


def delete_cart_item(request, cart_id):
	if request.user.is_authenticated:
		if request.headers.get('x-requested-with') == 'XMLHttpRequest':
			try:
				cart_item = Cart.objects.get(user=request.user, id=cart_id)
				if cart_item:
					cart_item.delete()
					return JsonResponse({ 'status' : 'Success', 'message': 'Item Deleted', 
						'cart_counter':get_cart_counter(request), 'cart_amount' : get_cart_amounts(request)   
						})

			except Cart.DoesNotExist:
				return JsonResponse({'status': 'Failed', 'message': 'No Cart Item'  })
		else:
			return JsonResponse({'status': 'Failed', 'message': 'Invalid Request'})


def search(request):
	if not 'address' in request.GET:
		return redirect ('marketplace')
	else:
		address = request.GET['address']
		latitude = request.GET['latitude']
		longitude = request.GET['longitude']
		radius = request.GET['radius']
		keyword = request.GET['keyword']

		#get vendors by food search
		fetch_vendors_by_product = Product.objects.filter(title__icontains=keyword, is_available=True).values_list('vendor', flat=True)
		vendors = Vendor.objects.filter(Q(id__in=fetch_vendors_by_product) | Q(vendor_name__icontains=keyword, is_approved=True, user__is_active=True))
		
		# vendors within a location radius
		if latitude and longitude and radius:
			pnt = GEOSGeometry('POINT(%s %s)' % (longitude, latitude))

			vendors = Vendor.objects.filter(Q(id__in=fetch_vendors_by_product) | Q(vendor_name__icontains=keyword, is_approved=True, user__is_active=True), 
				user_profile__location__distance_lte=(pnt, D(km=radius))).annotate(distance=Distance("user_profile__location" , pnt )).order_by("distance")
			
			for v in vendors:
				v.kms = round(v.distance.km, 1)

		#vendors = Vendor.objects.filter(vendor_name__icontains=keyword, is_approved=True, user__is_active=True)
		vendors_count = vendors.count()
		context = { 
			'vendors' : vendors , 
			'vendors_count': vendors_count, 
			'source_location': address ,
		}
		
		return render (request, 'marketplace/listings.html' , context)
	
@login_required(login_url='accounts:login')
def checkout(request):
	cart_items = Cart.objects.filter(user=request.user)
	cart_count = cart_items.count()
	if cart_count <= 0:
		return redirect("marketplace")

	user_profile = UserProfile.objects.get(user=request.user)

#pre-populate the user form
	default_values = {
		'first_name':request.user.first_name ,
		'last_name' : request.user.last_name ,
		'phone':request.user.phone_number,
		'email':request.user.email,
		'address':user_profile.address,
		'country':user_profile.country,
		'state': user_profile.state,
		'city': user_profile.city,
		'post_code':user_profile.postcode
	}

	form = OrderForm(initial=default_values)
	context = { 
		'form' : form, 
	    'cart_items' : cart_items ,
		}

	return render(request, 'marketplace/checkout.html' , context)

templates/marketplace/cart.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="main-section" style="height: 100vh;">
	<div class="page-section pt-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
					<div class="tabs-holder horizontal">
						<ul class="stickynav-tabs nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Cart Items</a></li>				
						</ul>
						<div class="tab-content">
							<div id="home" class="tab-pane in active">
								<div class="menu-itam-holder">	
									<div class="text-center p5" id="empty-cart" style="display: none;"> <h4>The Cart is Empty !</h4></div>
								
									<div id="menu-item-list-6272" class="menu-itam-list">	
										<ul>
										{% if cart_items %}	
										  {% for item in cart_items %}
											<li id="cart-item-{{item.id}}">
												<div class="image-holder"> 
													<a href="">
														<img src="{{ item.product.image.url }}" alt="">
													</a>
												</div>
												<div class="text-holder">
													<h6>{{ item.product }} &nbsp; &nbsp;  id: {{item.product.id}} </h6>
													<span style="word-wrap: break-word; max-width: 70%;"> {{ item.product.description }} </span>
													<a href="{% url 'vendor-detail' item.product.vendor.vendor_slug  %}" class="badge badge-warning">{{item.product.vendor}}</a>
												</div>
												<div class="price-holder">
													<span class="price">{{ item.product.price}} </span>
													<a 	href="#" class="decrease-cart" id="{{ item.id }}"  data-id="{{ item.product.id }}" data-url="{% url 'remove-cart-item' item.product.id %}"
													   	style="margin-right: 28px;" >
														<i class="icon-minus text-color"></i>
													</a>
													<label id="qty-{{item.product.id}}"> 0 </label> 
													<a href="#" class="add-to-cart" data-id="{{ item.product.id }}" data-url="{% url 'add-to-cart' item.product.id %}" >
														<i class="icon-plus4 text-color"></i>
													</a> 
													<a href="#" class="delete-cart-item" data-id="{{ item.id }}" data-url="{% url 'delete-cart-item' item.id %}" >
														<i class="icon-delete text-color"></i>
													</a> 
												</div>
											</li>
										  {% endfor %}										  
										{% else %}
										  <div class="text-center p5"> <h4>The Cart is Empty </h4></div>
										{% endif %}
										</ul>													
									</div>
								</div>
							</div>										
						</div>
					</div>
				</div>	

				<!--ORDER DETAILS -->
				<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
					<div class="tabs-holder horizontal">
						<ul class="stickynav-tabs nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Your Order</a></li>				
						</ul>
						<div class="tab-content">
							<div id="home" class="tab-pane in active">
								<div class="menu-itam-holder">
									<div>
										<ul>
											<li style="list-style-type: none;">
												Subtotal
												<span class="price float-right">
													<span class="currency">£</span>
													<span id="subtotal"> {{ subtotal }} </span>
												</span>
											</li>
											{% for key, value in tax_dict.items %}
												{% for i, j in value.items %}
													<li style="list-style-type: none;">
														{{ key }} <small>({{ i }}%)</small>
														<span class="price float-right">
															<span class="currency">£</span>
															<span id="tax-{{ key }}"> {{ j }} </span>
														</span>
													</li>
												{% endfor %}
											{% endfor %}
											<li style="list-style-type: none; font-weight: 600;">
												TOTAL
												<span class="price float-right">
													<span class="currency">£</span>
													<span id="total"> {{ grandtotal }} </span>
												</span>
											</li>
											<hr>
											<a href="{% url 'checkout' %}" class="btn btn-success">PROCEED TO CHECKOUT</a>
										</ul>
									</div> 
								</div>
							</div>										
						</div>
					</div>
				</div>
			</div>  <!-- row end -->
		</div>
	</div>     
</div>

{% for item in cart_items %}
	<span id="qty-{{item.product.id}}" class="itemQty " data-qty="{{item.quantity}}"> {{item.quantity}} </span>
{% endfor %} 

{% endblock %}

templates/marketplace/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="main-section" style="height: 70vh;">
	<div class="page-section pt-5">
		<div class="container">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<div class="tabs-holder horizontal">
						<ul class="stickynav-tabs nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Billing Address</a></li>				
						</ul>
						<div class="tab-content">
							<div id="home" class="tab-pane in active">
								<div class="menu-itam-holder">									
									<div id="menu-item-list-6272" class="menu-itam-list">	
                                        <form action="{% url 'orders:place-order' %}" method="POST" id="noRefreshForm">
                                            {% csrf_token %}
                                            <div class="row">
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    First Name : {{ form.first_name }}
                                                </div>
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    Last Name : {{ form.last_name }}
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    Phone No : {{ form.phone }}
                                                </div>
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    Email  : {{ form.email }}
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-lg-12 col-md-12 col-sm-12">                      
                                                    Address : {{ form.address }}
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    Country: {{ form.country }}
                                                </div>
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    Region  : {{ form.state }}
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    City : {{ form.city }}
                                                </div>
                                                <div class="form-group col-lg-6 col-md-6 col-sm-12">                      
                                                    Post Code  : {{ form.post_code }}
                                                </div>
                                            </div>
									</div>
								</div>
							</div>										
						</div>
					</div>
				</div>	

				<!--ORDER DETAILS -->
				<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<div class="tabs-holder horizontal">
						<ul class="stickynav-tabs nav nav-tabs">
							<li class="active"><a data-toggle="tab" href="#home"><i class="icon- icon-room_service"></i>Your Order</a></li>				
						</ul>
						<div class="tab-content">
							<div id="home" class="tab-pane in active">
								<div class="menu-itam-holder">

									<div id="menu-item-list-6272" class="menu-itam-list">	
										<ul>

										  {% for item in cart_items %}
											<li id="cart-item-{{item.id}}">
												<div class="image-holder"> 
													<a href="">
														<img src="{{ item.product.image.url }}" alt="">
													</a>
												</div>
												<div class="text-holder">
													<h6>{{ item.product }}</h6>
													<span style="word-wrap: break-word; max-width: 70%;"> {{ item.product.description }} </span>
													<a href="{% url 'vendor-detail' item.product.vendor.vendor_slug  %}" class="badge badge-warning">{{item.product.vendor}}</a>
												</div>
												<div class="price-holder">
													<label id="qty-{{item.product.id}}"  style="margin-right: 20px;"> 0 </label> 
													<span class="price">{{ item.product.price}} </span>

												</div>
											</li>
										  {% endfor %}										  


										</ul>													
									</div>
									<div>
										<ul>
											<li style="list-style-type: none;">
												Subtotal
												<span class="price float-right">
													<span class="currency">£</span>
													<span id="subtotal"> {{ subtotal }} </span>
												</span>
											</li>
											{% for key, value in tax_dict.items %}
												{% for i, j in value.items %}
													<li style="list-style-type: none;">
														{{ key }} <small>({{ i }}%)</small>
														<span class="price float-right">
															<span class="currency">£</span>
															<span id="tax-{{ key }}"> {{ j }} </span>
														</span>
													</li>
												{% endfor %}
											{% endfor %}
											<li style="list-style-type: none; font-weight: 600;">
												TOTAL
												<span class="price float-right">
													<span class="currency">£</span>
													<span id="total"> {{ grandtotal }} </span>
												</span>
											</li>
											<hr>
											<h5>SELECT PAYMENT METHOD</h5>
											<div class="payment-method">
												<labeL>
													<input type="radio" name="payment-method" value="PayPal">
													<img src="{% static 'images/PayPal.png' %}" alt="PayPal" width="100px">
												</labeL> 
												&nbsp; &nbsp;
												<label>
													<input type="radio" name="payment-method" value="stripe" >
													<img src="{% static 'images/stripe.png' %}" alt="stripe" width="100px">
												</labeL>
											</div>
											<span class="text-danger" id="payment-method-error"></span> 
                                            <hr>
                                                <button class="btn btn-success" onclick="return payMethodConfirm()">PLACE ORDER</button>
										</ul>
                                    </form>  <!-- FORM SUBMIT BUTTON FORM ENDS HERE-->

                                    </div> 
								</div>
							</div>										
						</div>
					</div>
				</div>
			</div>  <!-- row end -->
		</div>
	</div>     
</div>

<script>
    function payMethodConfirm(){
        var payMethod = $("input[name='payment-method']:checked").val()
        if(!payMethod){
            $('#payment-method-error').html("Select Payment Method!");
            return false;
        }else{
            var conf = confirm('You have selected '+payMethod+' as your preferred payment method.\nClick "OK" to continue.')
            if(conf == true){
                return true;
            }else{
                return false;
            }
        }
    }

    $('input[name=payment-method]').on('change', function(){
        $('#payment-method-error').html("");
    })
</script>



{% for item in cart_items %}
	<span id="qty-{{item.product.id}}" class="itemQty " data-qty="{{item.quantity}}">  </span>
{% endfor %} 

{% endblock %}

templates/marketplace/listings.html
{% extends 'base.html' %} {% load static %}

{%  block content %}
<div class="main-section" style="height:85vh;">
	<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 10px;margin-bottom: 0px;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="row">
						<aside class="col-lg-2 col-md-2 col-sm-12 col-xs-12">					
						</aside>
						<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
							<div class="listing-sorting-holder">
								<div class="row">
									<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
										<h4>{{ vendors_count }} Restaurant's found</h4>
									</div>
								</div>
							</div>
							<div class="listing simple">
								<ul>  
								{% for vendor in vendors %}
									<li style="line-height: 15px;">
										<div class="img-holder">
											<figure>
												{% if vendor.user_profile.profile_picture %}
													<a href="{% url 'vendor-detail' vendor.vendor_slug   %}"><img src="{{ vendor.user_profile.profile_picture.url }}" class="img-list wp-post-image" alt=""></a>
												{% else %}
													<a href="{% url 'vendor-detail' vendor.vendor_slug   %}"><img src="{% static 'images/default-profile.PNG' %}" class="img-list wp-post-image" alt=""></a>
												{% endif %}
											</figure>
											<span class="restaurant-status open"><em class="bookmarkRibbon"></em>open</span>
										</div>
										<div class="text-holder">
											<div class="post-title">
												<h5>
													<a href="{% url 'vendor-detail' vendor.vendor_slug   %}"> {{ vendor }}</a>
												</h5>
											</div>
												{% if vendor.user_profile.address %}
													<span><small class="">{{ vendor.user_profile.address}}</small> </span>
												{% endif %}
												<br>
												{% if source_location %}
													<span><small><b> {{vendor.kms}} kms </b> away from {{ source_location }}</small></span>  
												{% endif %}
											</div>
										<div class="list-option">
											<a href="{% url 'vendor-detail' vendor.vendor_slug   %}" class="viewmenu-btn text-color">View Menu</a>
										</div>
									</li>
								{% endfor %}
								</ul>
							</div>
						</div>
						<div class="section-sidebar col-lg-3 col-md-3 col-sm-12 col-xs-12">
							<div class="message-box" style="background-color: #fa9918;">
								<strong>I'm not Listed!</strong><span>is your restaurant or
									business not
									listed on our site</span>
								<a href="{% url 'accounts:registervendor' %}" class="request-btn">Add Your business!</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/marketplace/marketplace.html
{% extends 'base.html' %} {% load static %}

{%  block content %}
<div class="main-section">
	<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 10px;margin-bottom: 0px;">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="row">
						<aside class="col-lg-2 col-md-2 col-sm-12 col-xs-12">					
						</aside>
						<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12">
							<div class="listing-sorting-holder">
								<div class="row">
									<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
										<h4>{{ vendro_count }} Restaurant's found</h4>
									</div>
								</div>
							</div>
							<div class="listing simple">
								<ul>  
								{% for vendor in vendors %}
									<li style="line-height: 15px;">
										<div class="img-holder">
											<figure>
												{% if vendor.user_profile.profile_picture %}
													<a href="{% url 'vendor-detail' vendor.vendor_slug   %}"><img src="{{ vendor.user_profile.profile_picture.url }}" class="img-list wp-post-image" alt=""></a>
												{% else %}
													<a href="{% url 'vendor-detail' vendor.vendor_slug   %}"><img src="{% static 'images/default-profile.PNG' %}" class="img-list wp-post-image" alt=""></a>
												{% endif %}
											</figure>
											{% if vendor.is_open %} 
											<span class="restaurant-status open"><em class="bookmarkRibbon"></em>open</span>
											{% else %} 
											<span class="restaurant-status close"><em class="bookmarkRibbon"></em>closed</span>
											{% endif %} 
										</div>
										<div class="text-holder">
											<div class="post-title">
												<h5>
													<a href="{% url 'vendor-detail' vendor.vendor_slug   %}"> {{ vendor }}</a>
												</h5>
											</div>
												{% if vendor.user_profile.address %}
													<span><small class="">{{ vendor.user_profile.address}}</small> </span>
												{% else %}
													<span><small class=""> </small></span>
												{% endif %}
										</div>
										<div class="list-option">
											<a href="{% url 'vendor-detail' vendor.vendor_slug   %}" class="viewmenu-btn text-color">View Menu</a>
										</div>
									</li>
								{% endfor %}
								</ul>
							</div>
						</div>
						<div class="section-sidebar col-lg-3 col-md-3 col-sm-12 col-xs-12">
							<div class="message-box" style="background-color: #fa9918;">
								<strong>I'm not Listed!</strong><span>is your restaurant or
									business not
									listed on our site</span>
								<a href="{% url 'accounts:registervendor' %}" class="request-btn">Add Your business!</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}