accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.myAccount ),
    path('registeruser/', views.registerUser, name='registeruser'),
    path('registervendor/', views.registerVendor, name='registervendor'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('myaccount/', views.myAccount, name='myaccount'),
    path('customerdashboard/', views.customerDashboard, name='customerdashboard'),
    path('vendordashboard/', views.vendorDashboard, name='vendordashboard'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password_validate/<uidb64>/<token>' , views.reset_password_validate, name='reset_password_validate'),
    path('reset_password/', views.reset_password, name='reset_password'),
]

customers/urls.py
from django.urls import path
from accounts import views as accViews
from . import views

app_name = 'customers'

urlpatterns = [
    path('', accViews.customerDashboard, name="customer"),
    path('profile/' , views.customer_profile, name="cprofile"),
    path('myorders/', views.my_orders, name='cust-myorders'),
    path('order-detail/<int:pk>', views.order_detail, name='order-detail'),
]

mvstore/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from marketplace import views as mpViews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home") ,
    path('about/', views.about, name="about") ,
    path('accounts/', include('accounts.urls' ,  namespace="accounts")),
    path('customer/', include('customers.urls', namespace="customer")),
    path('vendor/', include('vendor.urls' ,  namespace="vendor")),
    path('marketplace/', include('marketplace.urls')) ,
    path('checkout/', mpViews.checkout, name="checkout"),
    path('orders/', include('orders.urls')) ,
    path('search/', mpViews.search, name="search" )
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('place-order/', views.place_order, name="place-order"),
    path('payments/', views.payments, name="payments"),
    path('order-complete/', views.order_complete, name='order-complete')
    # path('', views.orders, name="orders"),
]

templates/includes/alerts.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{message.tags}} show-notification" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
           <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/includes/cover.html
{% load static %}

<div class="page-section restaurant-detail-image-section background-header">
  <!-- Container Start -->
  <div class="container">
    <!-- Row Start -->
    <div class="row">
      <!-- Column Start -->
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="company-info-detail">
          <div class="company-info">
            <div class="img-holder">
              <figure>
                {% if vendor.user_profile.profile_picture %}
                  <img src="{{ vendor.user_profile.profile_picture.url }}" alt="">
                {% else %}
                <img src="{% static 'images/default-profile.PNG' %}" alt="">
                {% endif  %}

              </figure>
            </div>

            <div class="text-holder">
              <span class="restaurant-title">{{vendor.vendor_name}}</span>
              <div class="text">
                {% if vendor.user_profile.address %}
                  <i class="icon-location"></i>
                  <p>{{vendor.user_profile.address}}</p>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Column End -->
    </div>
    <!-- Row End -->
  </div>
  <!-- Container End -->
</div>

templates/includes/footer.html
		<!-- Footer Start -->
		<footer id="footer" class="footer-style-2" style="margin-top:25%">
			<div class="footer-widget">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="widget widget-newsletter">
								<div class="widget-title">
									<h5>Subscribe to our Newsletter</h5>
								</div>
								<div class="fieldset">
									<form action="#">
										<div class="field-holder">
											<label>
												<i class=" icon-envelope3"></i>
												<input type="text" class="field-input" placeholder=" Enter Your Email Address...">
											</label>
										</div>
										<div class="field-holder btn-holder">
											<input class="subscribe-btn bgcolor" type="submit" value="Sign Up">
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="copyright-sec">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="copyright-inner">
								<div class="copy-right">
									<p>© 2020 Foodbakery. All Rights Reserved. Developed By <a href="#">Rathan Kumar</a>
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div> <!-- /.cs-copyright -->
		</footer>
		<!-- Footer End -->

templates/includes/navbar.html
{% load static %}
<div class="wrapper">
    <!-- Header Start -->
    <header id="header">
        <div class="main-header">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <div class="logo">
                            <figure>
                                <a href="{% url 'home' %}" class="light-logo">
                                    <img src="{%  static 'extra-images/main-logo.png' %}" alt="FoodBakery">
                                </a>
                            </figure>
                        </div>

                        <div class="main-location ml-5">
                            <ul>
                                <li class="location-has-children choose-location">
                                    <form action="#">
                                        <input type="text" value="" id="location" name="location" placeholder="Your current location" autocomplete="off">
                                        <span id="foodbakery_radius_location_open" class="foodbakery-radius-location" onClick="getLocation()"><i class="icon-target5"></i></span>
                                    </form>

                                </li>
                            </ul>
                            </div>
                    </div>
                    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                        <div class="login-option">

                          {% if user.is_authenticated %}
                            <a href="{% url 'cart' %}" class="mr-2">
                                <i class="fa fa-shopping-cart text-danger" style="font-size:18px; top:5px; position:relative;"></i>
                                <span id="cart-counter"  class="badge badge-warning" style="border-radius: 50px; position: relative; bottom:10px; margin-left: -5px;">
                                    {{cart_count}}
                                </span>
                            </a>
                          {% endif %}

                            <a href="{% url 'marketplace'  %}" class="btn btn-outline-secondary text-uppercase font-weight-bold">marketplace</a> 
                          {% if user.is_authenticated %}
                            <a href="{% url 'accounts:myaccount' %}" class="cs-color cs-popup-joinus-btn login-popup" data-toggle="modal">My Account  </a> &nbsp; |
                            <a href="{% url 'accounts:logout' %}" class="cs-color cs-popup-joinus-btn login-popup" data-toggle="modal">Logout </a> &nbsp; |
                          {% else %}
                              <a href="{% url 'accounts:login' %}" class="cs-color cs-popup-joinus-btn login-popup" data-toggle="modal">Login  </a> &nbsp; |
                              <a href="{% url 'accounts:registeruser' %}" class="cs-color cs-popup-joinus-btn login-popup ml-0" data-toggle="modal">Register  </a>
                              <a href="{% url 'accounts:registervendor' %}" class="get-start-btn">Register Shop </a>
                          {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <script>
        var x = document.getElementById("location");

        var currentLocation = sessionStorage.getItem("currentLocation")

        if (currentLocation != "") {
            x.value = currentLocation
        }

        function getLocation() {
          if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
          } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
          }
        }
        
        function showPosition(position) {
            var lat = position.coords.latitude
            var lng = position.coords.longitude

            // API REQUEST TO GOOGLEMAPS API
            var GOOGLE_API_KEY = "{{ GOOGLE_API_KEY }}"
            var url = `https://maps.googleapis.com/maps/api/geocode/json?latlng=${lat},${lng}&key=${GOOGLE_API_KEY}`

            // make the ajax request
            $.ajax({
                url: url,
                type:"GET",
                success: function(response){
                    var currentLocation =  response.results[0].formatted_address
                    x.value = currentLocation
                    sessionStorage.setItem("currentLocation", currentLocation)
                    window.location=`?lat=${lat}&lng=${lng}`
                }

            })

        }
    </script>
        

templates/includes/sidebar-c.html
<div class="user-account-nav user-account-sidebar">
  <div class="user-nav-list">
    <ul>
      <li class="{% if '/accounts/customerdashboard/' == request.path  or '/customer/' == request.path %}active{% endif %}">
          <a href="{% url 'accounts:customerdashboard' %}"><i class="icon-dashboard3"></i>Dashboard</a>
      </li>
      <li class="{% if '/customer/myorders/' == request.path or '/customer/order-detail/' in request.path %}active{% endif %}">
        <a href="{% url 'customer:cust-myorders' %}"><i class="icon-add_shopping_cart"></i>My Orders</a>
      </li>
      <li class="{% if '/profile/' in request.path %} active {% endif %}" >
        <a href="{% url 'customers:cprofile' %}"><i class="icon-build"></i>Profile Settings</a>
      </li>
      <li><a class="logout-btn" href="{% url 'accounts:logout' %}"><i class="icon-log-out"></i>Signout</a></li>
    </ul>
  </div>
</div>

templates/includes/sidebar-v.html
<div class="user-account-nav user-account-sidebar">
  <div class="user-nav-list">
    <ul>
      <li class="{% if '/accounts/vendordashboard/' == request.path  or '/vendor/' == request.path %}active{% endif %}">
          <a href="{% url 'accounts:vendordashboard' %}"><i class="icon-dashboard3"></i>Dashboard</a>
      </li>
      <li class="{% if '/vendor/profile/' == request.path %}active{% endif %}">
        <a href="{% url 'vendor:vprofile' %}"><i class="icon-building"></i>My Store</a>
      </li>
      <li class="{% if '/vendor/menu-builder/' == request.path %}active{% endif %}">
        <a href="{% url 'vendor:menu-builder' %}"><i class="icon-menu5"></i>Menu Builder</a>
      </li>
      <li class="{% if '/vendor/opening-hours/' == request.path %}active{% endif %}">
        <a href="{% url 'vendor:opening-hours' %}"><i class="icon-menu5"></i>Opening Hours</a>
      </li>

      <li><a href="restaurant-orders.html"><i class="icon-add_shopping_cart"></i>Orders</a></li>
      <li><a href="restaurant-earnings.html"><i class="icon-money"></i>Earnings</a></li>
      <li><a href="restaurant-statement.html"><i class="icon-file-text22"></i>Statement</a></li>
      <li><a href="restaurant-change-password.html"><i class="icon-unlock-alt"></i>Change Password</a></li>
      <li><a class="logout-btn" href="registration.html"><i class="icon-log-out"></i>Signout</a></li>
    </ul>
  </div>
</div>