mvstore/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from marketplace import views as mpViews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home") ,
    path('about/', views.about, name="about") ,
    path('accounts/', include('accounts.urls' ,  namespace="accounts")),
    path('customer/', include('customers.urls', namespace="customer")),
    path('vendor/', include('vendor.urls' ,  namespace="vendor")),
    path('marketplace/', include('marketplace.urls')) ,
    path('checkout/', mpViews.checkout, name="checkout"),
    path('orders/', include('orders.urls')) ,
    path('search/', mpViews.search, name="search" )
    
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views

app_name = 'orders'

urlpatterns = [
    path('place-order/', views.place_order, name="place-order"),
    path('payments/', views.payments, name="payments"),
    path('order-complete/', views.order_complete, name='order-complete')
    # path('', views.orders, name="orders"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point



class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('user must have a valid email')

        if not username:
            raise ValueError('user must have a username')

        user  = self.model(
            email = self.normalize_email(email),
            username = username ,
            first_name = first_name,
            last_name = last_name )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(
            email=self.normalize_email(email),
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name,
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    VENDOR = 1
    CUSTOMER = 2

    ROLE_CHOICE = (
        (VENDOR, 'Vendor'),
        (CUSTOMER, 'Customer'),
    )

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    #required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now_add=True)

    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_supderadmin = models.BooleanField(default=False)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [ 'username' , 'first_name', 'last_name' ]


    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_role(self):
        if self.role == 1:
            user_role = 'Vendor'
        elif self.role == 2:
            user_role = 'Customer'
        return user_role


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/profile_pictures', blank=True, null=True )
    cover_photo = models.ImageField(upload_to='users/cover_photos', blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    state = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    postcode = models.CharField(max_length=9, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)
    location = gismodels.PointField(blank=True, null=True, srid=4326)
    create_at = models.DateTimeField(auto_now_add=True)
    modified_At = models.DateTimeField(auto_now=True)


    # srid ==> spactial refrence identifier
    # def full_address(self):
    #     return f'{self.address_line_1 } , {self.address_line_2} , {self.postcode}'

    def __str__(self):
        return self.user.email

    def save(self, *args, **kwargs):
        if self.latitude and self.longitude:
            self.location = Point(float(self.longitude) , float(self.latitude))
            return super(UserProfile, self).save(*args, **kwargs)
        return super(UserProfile, self).save(*args, **kwargs)
        

orders/models.py
from django.db import models
from accounts.models import User
from menu.models import Product


class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
        ('RazorPay', 'RazorPay'), # Only for Indian Students.
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed'),
        ('Cancelled', 'Cancelled'),
    )

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    order_number = models.CharField(max_length=20)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15, blank=True)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=50, blank=True)
    state = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=50)
    post_code = models.CharField(max_length=10)
    total = models.FloatField()
    tax_data = models.JSONField(blank=True, help_text = "Data format: {'tax_type':{'tax_percentage':'tax_amount'}}")
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(max_length=15, choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Concatenate first name and last name
    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def __str__(self):
        return self.order_number


class OrderedProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<!-- Google Font Family Link End -->

	<link rel="shortcut icon" href="{% static 'favicon.png' %}" type="image/x-icon">
	
	<!-- CSS -->
	<link href="{% static 'css/custom.css' %}" rel="stylesheet">
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}"  rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}"  rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" 
			integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" 
			crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link href="{% static 'css/bootstrap-slider.css' %}"  rel="stylesheet">

	<!-- Sweet Alert css CDN -->
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.12/dist/sweetalert2.min.css" 
			integrity="sha256-7jUS+MWeqkFdmW9ozkZ7mPagz+QmMbsBlt+Q3MsE+FU=" crossorigin="anonymous">



	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"   ></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
	{% if '/' == request.path or 'profile' in request.path %}
	  <script src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete"  defer></script>
	{% endif %}

	<script src="https://www.paypal.com/sdk/js?client-id={{PAYPAL_CLIENT_ID}}&currency=USD"></script>
	
	<script src="{% static 'js/custom.js' %}"></script>
	<!-- Sweet Alert JS & Css CDN -->
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.7.12/dist/sweetalert2.all.min.js"></script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>

	{% block page-style %}

	{% endblock %}

</head>

<body>
	{% include "includes/navbar.html" %}
	{% block content %}


	{% endblock %}
	{% include 'includes/footer.html'  %}
	<script src="{%  static 'js/scripts.js' %}"></script>
	<script src="{%  static 'js/functions.js' %}"></script>
</body>

</html>

templates/home-old.html
{% extends 'base.html' %} {% load static %}

{%  block content %}

		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin" style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url('{%static "extra-images/bg-image1.jpg" %}') no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder">
								<form>
									<div class="row">
										<div class="col-lg-6 col-md-6 col-sm-5 col-xs-12">
											<div class="field-holder">
												<input type="text" placeholder="Resturant name">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out">
															<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
															<span id="foodbakery_radius_location_open333" class="foodbakery-radius-location"><i class="icon-target5"></i></span>
															<input type="text" class="location-field-text filter" placeholder="All Locations">
														</div>
														<div class="select-location" id="foodbakery-radius-range333" style="display: none;">
															<div class="select-popup popup-open">
																<a id="location_close_popup333" href="javascript:0;" class="location-close-popup">
																	<i class="icon-times"></i></a>
																<input type="hidden" class="foodbakery-radius" name="foodbakery_radius" value="10">
																<p>Show with in</p>
																<input id="ex16b333" type="text" data-value="10" value="10" style="display: none;">
																<script>
																	jQuery(document).ready(function () {
																		var elem = jQuery("#ex16b333");
																		if (elem.length != "") {
																			elem.slider({
																				step: 1,
																				min: 0,
																				max: 500,
																				value: 10,
																			});
																			elem.on("slideStop", function () {
																				var rang_slider_val = elem.val();
																				jQuery("#ex16b333CurrentSliderValLabel").html(rang_slider_val);
																				jQuery("#range-hidden-foodbakery-radius333").val(rang_slider_val);
																				//foodbakery_restaurant_content("333");
																			});
																			elem.on("slide", function () {
																				jQuery("#ex16b333CurrentSliderValLabel").html(elem.val());
																			});
																		}

																		$("#foodbakery_radius_location_open333").click(function () {
																			$("#foodbakery-radius-range333").show();
																		});
																		$("#location_close_popup333").click(function () {
																			$("#foodbakery-radius-range333").hide();
																		});
																	});
																</script>
																<span>Miles: <span id="ex16b333CurrentSliderValLabel">10</span></span><br>
																<p class="my-location">of <i class="cs-color icon-location-arrow"></i><a id="foodbakery-geo-location-all" class="cs-color foodbakery-geo-location313324" href="javascript:void(0)">My location</a></p>
															</div>
														</div>
													</li>
												</ul>
											</div>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<div class="field-holder">
												<input type="submit" value="Search">
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>

					</div>
				</div>
			</div>
			<!-- Main Search End -->

			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="company-logo">
								<ul>
									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/listing-logo18.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/fb-restaurant-02.jpg' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/fb-restaurant-04.jpg' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/fb-restaurant-06.jpg' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>

									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/listing-logo09.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/listing-logo18.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
									<li class="has-border">
										<figure>
											<a href="#"><img src="{%  static 'extra-images/fb-restaurant-09.png' %}" class="attachment-full size-full wp-post-image" alt=""></a>
										</figure>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure><a href="#"><img src="{%  static 'extra-images/listing-logo18.png' %}" class="img-thumb wp-post-image" alt=""></a></figure>
												<span class="restaurant-status close">
													<em class="bookmarkRibbon"></em>Close
												</span>
											</div>
											<div class="text-holder">
												<div class="list-rating">
													<div class="rating-star">
														<span class="rating-box" style="width: 100%;"></span>
													</div>
													<span class="reviews">(1)</span>
												</div>
												<div class="post-title">
													<h5>
														<a href="listing-detail.html">Restaurant Demo</a>
														<span class="sponsored text-color">Sponsored</span>
													</h5>
												</div>
												<address> <span>Type of food : </span> Apple Juice</address>
											</div>

										</div>
									</li>
									<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
										<div class="list-post featured">
											<div class="img-holder">
												<figure><a href="#"><img src="{%  static 'extra-images/listing-logo09.png' %}" class="img-thumb wp-post-image" alt=""></a></figure>
												<span class="restaurant-status open">
													<em class="bookmarkRibbon"></em>open
												</span>
											</div>
											<div class="text-holder">
												<div class="list-rating">
													<div class="rating-star">
														<span class="rating-box" style="width: 100%;"></span>
													</div>
													<span class="reviews">(1)</span>
												</div>
												<div class="post-title">
													<h5>
														<a href="listing-detail.html">Classic Restaurant</a>
														<span class="sponsored text-color">Sponsored</span>
													</h5>
												</div>
												<address> <span>Type of food : </span> Chicken Roast, Chines
													Soup, Cold
													Coffee, Cold Drink, Hot Dogs</address>
											</div>

										</div>
									</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Choose From Most Popular Listing End -->

			<!-- Home Pages Elements End  -->
		</div>

{% endblock %}

templates/home.html
{% extends 'base.html' %} {% load static %}

{% block page-style %}
	<style>
		.cover-picture-div {
			/* background-color: pink; */
			background: url("{% static 'extra-images/bg-image1.jpg' %}") no-repeat center / cover; 
			padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; 
		}
		.main-home-header{
			font-size:40px; color:#505050; text-transform:uppercase; line-height:50px; margin-bottom:25px; text-align:center;
		}
		.main-home-txt{
			font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;
		}
		.top-vendors-div {
			margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;
		}	
	</style>
{% endblock %}

{%  block content %}

<div class="main-section">
	<!-- Home Pages Elements Strat -->
	<!-- Main Search Start -->
	<div class="page-section nopadding cs-nomargin cover-picture-div ">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title">
						<h1 class="main-home-header">
							We are in the business of food<br>our restaurants do</h1>
						<p class="main-home-txt">
							Ridiculus sociosqu
							cursus neque cursus curae ante scelerisque vehicula.</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
					<div class="main-search fancy bg-holder">
						<form action="{% url 'search' %}" method="GET">
							<div class="row">
								<div class="col-lg-4 col-md-4 col-sm-3 col-xs-12">
									<div class="field-holder">
										<input name="keyword"  type="text" placeholder="Resturant name or Food type">
									</div>
								</div>
								<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
									<div class="field-holder">
										<ul>
											<li class="select-location">
												<div class="foodbakery-locations-fields-group foodbakery-focus-out">
													<span class="foodbakery-search-location-icon"><i class="icon-location"></i></span>
													<input type="text" class="location-field-text filter" name="address" id="id_address" placeholder="All Locations">
													<input type="hidden" name="longitude" id="id_longitude">
													<input type="hidden" name="latitude" id="id_latitude">
												</div>
											</li>
										</ul>
									</div>
								</div>
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
									<select name="radius" id="radius" style="height:50px;" required> 
										<option value="" selected>Choose Radius </option>
										<option value="3"> 3km </option>
										<option value="5"> 5km </option>
										<option value="10"> 10km </option>
										<option value="15"> 15km </option>
										<option value="20"> 20km </option>
										<option value="30"> 30km </option>
									</select>
								</div>
								<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
									<div class="field-holder">
										<input type="submit" value="Search">
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Main Search End -->

	<!-- Top Restarurants Section Start -->
	<div class="page-section nopadding cs-nomargin top-vendors-div">
		<div class="container  align-center">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title align-left">
						<h2>Top Restaurants Near You</h2>
						<p>Explore restaurants, bars, and cafés by locality</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="company-logo">
						<ul>
							{% for vendor in vendors %}
							<li class="has-border">
								<h3>{{vendor.vendor_name}}</h3>
								<figure>
									{% if vendor.user_profile.profile_picture %}
										<a href="{% url 'vendor-detail' vendor.vendor_slug   %}">
											<img src="{{ vendor.user_profile.profile_picture.url }}" class="attachment-full size-full wp-post-image" alt="">
										</a>
									{% else %}
										<a href="{% url 'vendor-detail' vendor.vendor_slug   %}">
											<img src="{% static 'images/default-profile.PNG' %}" class="attachment-full size-full wp-post-image" alt="">
										</a>
									{% endif %}
								</figure>  
							</li>
							{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Top Restarurants Section End -->
	<!-- Choose From Most Popular Listin Start -->
	<div class="page-section nopadding cs-nomargin top-vendors-div">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="element-title align-center">
						<h2>Choose From Most Popular Restaurants</h2>
						<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
					</div>
				</div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
					<div class="listing fancy">
						<ul class="row">
						{% for vendor in vendors %}
							<li class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
								<div class="list-post featured">
									<div class="img-holder">
										<figure>

											<a href="{% url 'vendor-detail' vendor.vendor_slug   %}">

											  {% if vendor.user_profile.profile_picture %}
												<img src="{{ vendor.user_profile.profile_picture.url }}" class="img-thumb wp-post-image" alt="">
											  {% else %}
												<img src="{% static 'images/default-profile.PNG' %}" class="img-thumb wp-post-image" alt="">
											  {% endif %}
											</a>
										</figure>
										{% if vendor.is_open %}
										<span class="restaurant-status open"><em class="bookmarkRibbon"></em>open </span>
										{% else %}
										<span class="restaurant-status close"><em class="bookmarkRibbon"></em>closed </span>
										{% endif %}

									</div>
									<div class="text-holder">
										<div class="post-title">
											<h5> <a href="{% url 'vendor-detail' vendor.vendor_slug   %}"> {{vendor}} </a> </h5>
										</div>
										{% if vendor.user_profile.city  %}
											<span> {{vendor.user_profile.city}} {{vendor.user_profile.state}}  {{vendor.user_profile.postcode}}</span>
										{% endif %}
										<br>
										{% if vendor.kms %}
											<span><b>{{ vendor.kms }} away</b></span>
										{% endif %}
										<address></address>
									</div>
								</div>
							</li>
						{% endfor %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Choose From Most Popular Listing End -->

	<!-- Home Pages Elements End  -->
</div>

{% endblock %}